#if defined(__GFORTRAN__) || defined(NAGFOR)
#  define PASTE(a) a
#  define CAT(a,b) PASTE(a)b
#  define CAT3(a,b,c) CAT(a,b)c
#  define CAT4(a,b,c,d) CAT3(a,b,c)d
#else
#  define PCAT(a,b,c,d) a ## b ## c ## d
#  define CAT(a,b) PCAT(a,b,,)
#  define CAT3(a,b,c) PCAT(a,b,c,)
#  define CAT4(a,b,c,d) PCAT(a,b,c,d)
#endif

#define GLMFF_CLIP_CONTROL_ZO_BIT (1 << 0)
#define GLMFF_CLIP_CONTROL_NO_BIT (1 << 1)
#define GLMFF_CLIP_CONTROL_LH_BIT (1 << 2)
#define GLMFF_CLIP_CONTROL_RH_BIT (1 << 3)

#define GLMFF_CLIP_CONTROL_LH_ZO (GLMFF_CLIP_CONTROL_LH_BIT | GLMFF_CLIP_CONTROL_ZO_BIT)
#define GLMFF_CLIP_CONTROL_LH_NO (GLMFF_CLIP_CONTROL_LH_BIT | GLMFF_CLIP_CONTROL_NO_BIT)
#define GLMFF_CLIP_CONTROL_RH_ZO (GLMFF_CLIP_CONTROL_RH_BIT | GLMFF_CLIP_CONTROL_ZO_BIT)
#define GLMFF_CLIP_CONTROL_RH_NO (GLMFF_CLIP_CONTROL_RH_BIT | GLMFF_CLIP_CONTROL_NO_BIT)

#if defined(GLMFF_FORCE_DEPTH_ZERO_TO_ONE)
#  if defined(GLMFF_FORCE_LEFT_HANDED)
#    define GLMFF_CONFIG_CLIP_CONTROL GLMFF_CLIP_CONTROL_LH_ZO
#  else
#    define GLMFF_CONFIG_CLIP_CONTROL GLMFF_CLIP_CONTROL_RH_ZO
#  endif
#else
#  if defined(GLMFF_FORCE_LEFT_HANDED)
#    define GLMFF_CONFIG_CLIP_CONTROL GLMFF_CLIP_CONTROL_LH_NO
#  else
#    define GLMFF_CONFIG_CLIP_CONTROL GLMFF_CLIP_CONTROL_RH_NO
#  endif
#endif

